### PR TITLE
[#15671] Create docs layout and base components

### PR DESCRIPTION
**Pull request by willjthorp**
Part of https://github.com/Leadfeeder/issue-tracker/issues/15671

Creates the base docs layout and components in the addons dummy app.

Uses tailwind for styling, and ember-prism for code snippet highlighting. Checkout and run the branch locally to see it in action.

Screenshot:

Screenshot 2020-11-03 at 16 35 14

### CODE REVIEW

**Comment by willjthorp** [comment]
:white_check_mark: Review @Leadfeeder/frontend

**Comment by willjthorp** [comment]
For some reason it's not allowing me to tag specific people for review so just adding the frontend squad if anyone can take a look please 👍

**Review by netes — APPROVED** [review]
Looks cool :100: Nice place to start.

**Review by jbandura — APPROVED** [review]
Looks good 👍

**Pull request merged**
